package demo7;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo7.Palindromi.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.02.25 03:18:26 // Generated by ComTest
 *
 */
public class PalindromiTest {



  // Generated by ComTest BEGIN
  /** testPalindromi15 */
  @Test
  public void testPalindromi15() {    // Palindromi: 15
    assertEquals("From: Palindromi line: 16", false, palindromi("kala")); 
    assertEquals("From: Palindromi line: 17", true, palindromi("1221")); 
    assertEquals("From: Palindromi line: 18", true, palindromi("abba")); 
    assertEquals("From: Palindromi line: 19", false, palindromi("jeeja")); 
  } // Generated by ComTest END
}